import Head from "next/head";

import Header from "../components/Header";


import type { NextPage } from "next";


const Contact: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>wrathCodes - Contact</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-white to-gray-200">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 mt-12">
          <h2 className="text-5xl font-extrabold tracking-tight text-violet-500 sm:text-[3rem]">
            Contact
          </h2>
          <div className="flex flex-row justify-center items-center w-full ">
            <ContactForm />
          </div>
        </div>
      </main>
    </>
  );
};

export default Contact;

// Contact Form
const ContactForm = () => {
  return (
    <div className="py-10 px-6 sm:px-5 lg:col-span-2 xl:p-12 w-full max-w-3xl">
      <h3 className="text-lg text-violet-500 font-bold text-center">Send me a message</h3>
      <form action="#" method="POST" className="mt-6 grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">
        <div>
          <label htmlFor="first-name" className="block text-sm font-semibold text-violet-500">
            First name
          </label>
          <div className="mt-1">
            <input
              type="text"
              name="first-name"
              id="first-name"
              autoComplete="given-name"
              className="block w-full cursor-pointer rounded-md border border-transparent bg-gray-50 py-2 pl-2 pr-3 text-sm placeholder-gray-400 focus:border-violet-500 focus:bg-violet-100 focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
            />
          </div>
        </div>
        <div>
          <label htmlFor="last-name" className="block text-sm font-semibold text-violet-500">
            Last name
          </label>
          <div className="mt-1">
            <input
              type="text"
              name="last-name"
              id="last-name"
              autoComplete="family-name"
              className="block w-full cursor-pointer rounded-md border border-transparent bg-gray-50 py-2 pl-2 pr-3 text-sm placeholder-gray-400 focus:border-violet-500 focus:bg-violet-100 focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
            />
          </div>
        </div>
        <div>
          <label htmlFor="email" className="block text-sm font-semibold text-violet-500">
            Email
          </label>
          <div className="mt-1">
            <input
              id="email"
              name="email"
              type="email"
              autoComplete="email"
              className="block w-full cursor-pointer rounded-md border border-transparent bg-gray-50 py-2 pl-2 pr-3 text-sm placeholder-gray-400 focus:border-violet-500 focus:bg-violet-100 focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
            />
          </div>
        </div>
        <div>
          <div className="flex justify-between">
            <label htmlFor="phone" className="block text-sm font-semibold text-violet-500">
              Phone
            </label>
            <span id="phone-optional" className="text-sm text-gray-500">
              Optional
            </span>
          </div>
          <div className="mt-1">
            <input
              type="text"
              name="phone"
              id="phone"
              autoComplete="tel"
              className="block w-full cursor-pointer rounded-md border border-transparent bg-gray-50 py-2 pl-2 pr-3 text-sm placeholder-gray-400 focus:border-violet-500 focus:bg-violet-100 focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
              aria-describedby="phone-optional"
            />
          </div>
        </div>
        <div className="sm:col-span-2">
          <label htmlFor="subject" className="block text-sm font-semibold text-violet-500">
            Subject
          </label>
          <div className="mt-1">
            <input
              type="text"
              name="subject"
              id="subject"
              className="block w-full cursor-pointer rounded-md border border-transparent bg-gray-50 py-2 pl-2 pr-3 text-sm placeholder-gray-400 focus:border-violet-500 focus:bg-violet-100 focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
            />
          </div>
        </div>
        <div className="sm:col-span-2">
          <div className="flex justify-between">
            <label htmlFor="message" className="block text-sm font-semibold text-violet-500">
              Message
            </label>
          </div>
          <div className="mt-1">
            <textarea
              id="message"
              name="message"
              rows={4}
              className="block w-full cursor-pointer rounded-md border border-transparent bg-gray-50 py-2 pl-2 pr-3 text-sm placeholder-gray-400 focus:border-violet-500 focus:bg-violet-100 focus:text-gray-900 focus:placeholder-gray-500 focus:outline-none focus:ring-violet-500 sm:text-sm"
              aria-describedby="message-max"
              defaultValue={''}
            />
          </div>
        </div>
        <div className="sm:col-span-2 sm:flex sm:justify-end">
          <button
            type="submit"
            className="rounded-md bg-violet-500 px-10 py-3 font-semibold text-white no-underline transition hover:bg-violet-900 text-center cursor-pointer max-w-xs mx-auto"
          >
            Submit
          </button>
        </div>
      </form>
    </div>
  );
}