import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import sideLogo from "../../public/wrathCodes_side_logo.svg";
import Header from "../components/Header";
import { trpc } from "../utils/trpc";

import type { NextPage } from "next";
const Home: NextPage = (props) => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>wrathCodes - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-white to-gray-200">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Image src={sideLogo} alt="wrathCodes" width={300} height={300} />
          <h1 className="text-5xl font-extrabold tracking-tight text-gray-900 sm:text-[5rem]">
            wrath<span className="text-violet-500">Codes</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Card
              title="A bit about me"
              href="/about"
              description="Just the gist of what you need to know before you go any further into the rabbit hole."
            />
            <Card
              title="Blog"
              href="/blog"
              description="A collection of articles I've written on various topics."
            />
            <Card
              title="Story"
              href="/story"
              description="A in depth look at my journey into the world of web development."
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;


interface ICard {
  title: string;
  href: string;
  description: string;
}

const Card = ({ title, href, description }: ICard) => {
  return (
    <Link
      className="flex max-w-xs flex-col gap-4 rounded-xl bg-transparent p-4  hover:bg-violet-500/20 border-2 hover:border-violet-500 group transition-all duration-200 ease-in-out"
      href={href}
    >
      <h3 className="text-2xl font-bold group-hover:text-violet-900 transition-all duration-200 ease-in-out">
        {title}
      </h3>
      <div className="text-lg">
        {description}
      </div>
    </Link>
  )
};