import Head from "next/head";
import {
  SiExpress,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";

import Header from "../components/Header";

import type { NextPage } from "next";

const icons = [
  {
    title: "HTML",
    icon: <SiHtml5 />,
  },
  {
    title: "CSS",
    icon: <SiHtml5 />,
  },
  {
    title: "JavaScript",
    icon: <SiJavascript />,
  },
  {
    title: "TailwindCSS",
    icon: <SiTailwindcss />,
  },
  {
    title: "React",
    icon: <SiReact />,
  },
  {
    title: "NextJS",
    icon: <SiNextdotjs />,
  },
  {
    title: "TypeScript",
    icon: <SiTypescript />,
  },
  {
    title: "NodeJS",
    icon: <SiNodedotjs />,
  },
  {
    title: "MongoDB",
    icon: <SiMongodb />,
  },
  {
    title: "ExpressJS",
    icon: <SiExpress />,
  },
  {
    title: "PostgreSQL",
    icon: <SiPostgresql />,
  },
  {
    title: "Prisma",
    icon: <SiPrisma />,
  },
  {
    title: "Git",
    icon: <SiGit />,
  },
]

const experiences = [
  {
    title: "Software Engineer",
    company: "Cognizant",
    start: "June 2021",
    end: "Present",
    description: "Working as a Software Engineer in Cognizant",
  },
  {
    title: "Software Engineer",
    company: "Microsoft",
    start: "June 2021",
    end: "August 2022",
    description: "Working as a Software Engineer in Microsoft",
  },
  {
    title: "Software Engineer",
    company: "Google",
    start: "January 2021",
    end: "May 2021",
    description: "Working as a Software Engineer in Google",
  },
]

const Resume: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>wrathCodes - Resume</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-white to-gray-200">
        <div className="container flex flex-col items-center justify-center gap-4 px-4 mt-12">
          <h2 className="text-5xl font-extrabold tracking-tight mb-4 text-violet-500 sm:text-[3rem]">
            Resume
          </h2>
          <Divider title="Skills" />
          <div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5  md:gap-8 mb-16 px-5 py-10 rounded-lg bg-violet-500/10">
            {icons.map((icon) => (
              <Technololy key={icon.title} {...icon} />
            ))}
          </div>
          <Divider title="Experience" />
          <div className="flex flex-col items-center gap-4">
            {experiences.map((experience) => (
              <Experience key={experience.title} {...experience} />
            ))}
          </div>
        </div>

      </main >
    </>
  );
}

export default Resume;

interface ITechnology {
  title: string;
  icon: JSX.Element;
}

const Technololy = ({ title, icon }: ITechnology) => {
  return (
    <div className="flex flex-col items-center gap-2">
      <div className="flex text-5xl mb-1 items-center justify-center rounded-full text-violet-800/75">
        {icon}
      </div>
      <div className="text-sm font-semibold text-gray-600">{title}</div>
    </div>
  );
};

interface IDivider {
  title: string;
}

const Divider = ({ title }: IDivider) => {
  return (
    <div className="flex flex-row items-center justify-center gap-4">
      <span className="w-full px-5 py-0.5 bg-violet-500 md:px-16 lg:px-24 xl:px-32 "></span>
      <div className="justify-center text-center text-violet-800/75 font-semibold text-2xl">{title}</div>
      <span className="w-full px-5 py-0.5 bg-violet-500 md:px-16 lg:px-24 xl:px-32 "></span>
    </div>
  )
};

interface IExperience {
  title: string;
  company: string;
  start: string;
  end: string;
  description: string;
}

const Experience = ({ title, company, start, end, description }: IExperience) => {
  return (
    <div className="flex flex-col items-center gap-4">
      <div className="flex flex-col items-center gap-2">
        <div className="text-2xl font-semibold text-gray-600">{title}</div>
        <div className="text-sm font-semibold text-gray-600">{company}</div>
      </div>
      <div className="flex flex-row items-center justify-center gap-4">
        <div className="text-sm font-semibold text-gray-600">{start}</div>
        <div className="text-sm font-semibold text-gray-600">-</div>
        <div className="text-sm font-semibold text-gray-600">{end}</div>
      </div>
      <div className="text-sm font-semibold text-gray-600">{description}</div>
    </div>
  );
};