import Head from "next/head";

import Header from "../components/Header";

import type { NextPage } from "next";

const Story: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>wrathCodes - Story</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-white to-gray-200">
        <div className="container mt-16 flex flex-col items-center justify-center gap-12 px-4">
          <h2 className="md:text-md text-sm font-extrabold text-violet-500 lg:text-xl xl:text-2xl">
            Hi, let me introduce myself...
          </h2>
          <div className="mb-10 grid grid-cols-1 items-center gap-2 px-5 sm:grid-cols-1 md:gap-2">
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I'm <span className="font-semibold text-violet-500">Raphael</span>, a 31 year old software developer from
              Brazil. But it wasn't always like this.{" "}
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I started persuing a career in software development in 2010, when I was 19 years old. I was a student at
              the time, and I was studying <span className="font-semibold text-violet-500">Computer Science</span> at
              the Pontifical Catholic University of Rio de Janeiro. I was also taking
              <span className="font-semibold text-violet-500"> 3D</span> modeling classes at the same time.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I was really enjoying it. Maybe it was because I was learning something new, or maybe it was because I was
              learning something that I could use to create something that I could see imidiatly and I wasn't getting
              the same from the Computer Science classes. So I decided to{" "}
              <span className="font-semibold text-violet-500">drop out</span> of the Computer Science course and persue
              a career in 3D modeling.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              In a matter of months I had already secured my student visa to study 3D modeling in the United States, I
              found a place to live, and I was ready to go. That adventure started on July of 2012. And there I was, in
              the United States, ready to start my new life. It actually went everything almolt as planned until it
              didn't. I was studying at <span className="font-semibold text-violet-500">Full Sail University</span>, and
              I was really enjoying it. I was learning a lot, and I was making a lot of friends, and creating a lot of
              connections.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              A few years passed, I graduated from Full Sail University, and I was ready to start my career as a 3D
              modeler. Got a <span className="font-semibold text-violet-500">internship </span>
              at the Finals Department of my degree program. It lasted 6 months, and it made a huge impact on my life.
              Right after that I got a job at a small 3D modeling studio as a Remote 3D Hard Surface modeler.{" "}
              <span className="font-semibold text-violet-500">But it wasn't paying the bills</span>. I{" "}
              <span className="font-semibold text-violet-500">quit</span> that job and I started working as{" "}
              <span className="font-semibold text-violet-500">Game Tester</span>.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              First I worked in the <span className="font-semibold text-violet-500">localization team</span> checking if
              chinese games translated to english were correct. Then I worked in the QA team of team Scorpio for
              Experia. <span className="font-semibold text-violet-500">I was working on the Xbox One X</span>. I was
              testing games, and I was making sure that they were working as intended. I was also testing the Xbox One X
              itself. I was making sure that the hardware was working as intended, cheking if the games were hitting the
              spected frame rates, and if the games were using the hardware to its full potential.
            </p>
            <p className="md:text-md my-4 max-w-3xl text-center text-xs font-extrabold text-violet-500">
              Remember when I said sad everything went well until it didn't?
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              After all that came the end of <span className="font-semibold text-violet-500">2017</span>. My work permit
              was about to expire, and <span className="font-semibold text-violet-500">I had to go back to Brazil</span>
              . I was really sad about it, but I had to go back. I had to go back to Brazil. I tried getting back into{" "}
              <span className="font-semibold text-violet-500">3D modeling</span>, but I couldn't find a job and the{" "}
              <span className="font-semibold text-violet-500">joy was gone</span>. So, at the end of
              <span className="font-semibold text-violet-500"> 2021</span>, I decided to fall back into something I
              started many years ago, <span className="font-semibold text-violet-500">programming</span>.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I started learning programming again. I started with{" "}
              <span className="font-semibold text-violet-500">Python</span>, taking the{" "}
              <span className="font-semibold text-violet-500">IBM Data Science Professional Certificate</span> on
              Coursera. I thought that I could use that knowledge to get a job as a{" "}
              <span className="font-semibold text-violet-500">Data Scientist</span>. But I was wrong. To be honest what
              I learned from that course was that{" "}
              <span className="font-semibold text-violet-500">Data Science is boring</span>. My dad asked if I could
              help him with his insurance brokerage business. He had a lot of data that he needed to organize, and he
              needed a way to do it. I said let's do it.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I tried building a desktop application with <span className="font-semibold text-violet-500">Python</span>,
              but to be honest <span className="font-semibold text-violet-500">I had no idea what I was doing</span>. I
              was just following tutorials about the Kivy framework. Then I figure a Web Application would be better. I
              started learning <span className="font-semibold text-violet-500">Django</span>. But nowhere I was told I'd
              need to learn <span className="font-semibold text-violet-500">HTML, CSS, and JavaScript</span>. So I dove
              into those technologies as well. I was learning a lot. Again doing a lot of tutorials. But never creating
              things from scratch. So finally I decided to{" "}
              <span className="font-semibold text-violet-500">give it another try</span> on my dad's problem.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I did the <span className="font-semibold text-violet-500">jankiest </span>thing ever. I created a basic
              CRUD application with <span className="font-semibold text-violet-500">NodeJS, Express, EJS</span> and{" "}
              <span className="font-semibold text-violet-500">Bootstrap</span> on the front end. It was definitely not
              the best way to do it, but it worked. I was able to create a{" "}
              <span className="font-semibold text-violet-500">Web Application</span> that could help my dad organize his
              data. But then he wanted to be way more dynamic. Because of that I went down the{" "}
              <span className="font-semibold text-violet-500">React rabbit hole</span>.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I learned the basics, how to handle state and how to create stores(using{" "}
              <span className="font-semibold text-violet-500">Redux</span>) in order to make the second version of the
              applacation for my dad. I was able to create a system, this time using{" "}
              <span className="font-semibold text-violet-500">React, Redux, NodeJS, Express, MongoDB</span> and
              <span className="font-semibold text-violet-500"> TailwindCSS</span>. It was a lot better than the first
              version. But I was still not satisfied. Single page application for what I wanted to do, wasn't the right
              path. So I decided to learn <span className="font-semibold text-violet-500">NextJS</span>.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              I started then experimenting with <span className="font-semibold text-violet-500">NextJs</span>. Switched
              to <span className="font-semibold text-violet-500">PrismaORM</span> from{" "}
              <span className="font-semibold text-violet-500">Mongoose</span> in order to work with{" "}
              <span className="font-semibold text-violet-500">SQL </span>and learned{" "}
              <span className="font-semibold text-violet-500">Typescript </span>in order to have{" "}
              <span className="font-semibold text-violet-500">typesafety</span>. Honestly, I felt like I{" "}
              <span className="font-semibold text-violet-500"></span>leveled up. Following that, I learned about{" "}
              <span className="font-semibold text-violet-500">Clean Code</span> and the principles of{" "}
              <span className="font-semibold text-violet-500">S.O.L.I.D.</span>. I started, once again, the project,
              this time I created a backend with <span className="font-semibold text-violet-500">NodeJs</span>,{" "}
              <span className="font-semibold text-violet-500">Express</span>, integrated it with{" "}
              <span className="font-semibold text-violet-500">NextJs</span> in the frontend. In the frontend I used{" "}
              <span className="font-semibold text-violet-500">ReactQuery</span> to get and update data and{" "}
              <span className="font-semibold text-violet-500">TailwindCSS</span> to style the pages. I finally felt that
              I was able to create something consistent and usable in{" "}
              <span className="font-semibold text-violet-500"></span>production, but the project didn't go forward. My
              dad's company decided to use an <span className="font-semibold text-violet-500">Insuranse CRM</span>{" "}
              without integration with their website.
            </p>
            <p className="md:text-md my-4 max-w-3xl text-center text-xs font-extrabold text-violet-500">
              Well, I decided to leave a few things out. But they're really important.
            </p>
            <p className="md:text-md max-w-3xl indent-14 text-xs text-gray-700">
              In the end of <span className="font-semibold text-violet-500">2019</span> I met my{" "}
              <span className="font-semibold text-violet-500">wife</span>,{" "}
              <span className="font-semibold text-violet-500">Raquel</span>. She's{" "}
              <span className="font-semibold text-violet-500">perfect</span>. She got me on a better path and{" "}
              <span className="font-semibold text-violet-500">pushes</span> me to become a{" "}
              <span className="font-semibold text-violet-500">better person</span> everyday. It's been a little bit over{" "}
              <span className="font-semibold text-violet-500">three years</span> since we started dating and a few
              things happened since then. I got a <span className="font-semibold text-violet-500">job</span> with
              another insurance brokerage company, we got <span className="font-semibold text-violet-500">married</span>{" "}
              a little over <span className="font-semibold text-violet-500">a year ago</span>, and we just had a baby{" "}
              <span className="font-semibold text-violet-500">new born</span>, named{" "}
              <span className="font-semibold text-violet-500">Ravi</span>. They are{" "}
              <span className="font-semibold text-violet-500">my everything</span>.
              <p className="md:text-md my-4 max-w-3xl text-end text-xs font-extrabold text-violet-500">
                January, 09th 2023
              </p>
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Story;
