import Head from "next/head";

import Header from "../components/Header";


import type { NextPage } from "next";

const Story: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>wrathCodes - Story</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-white to-gray-200">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 mt-16">
          <h2 className="text-sm font-extrabold text-violet-500 md:text-md lg:text-xl xl:text-2xl">
            Hi,
            let me introduce myself...
          </h2>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-1 md:gap-2 items-center mb-10 px-5">
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I'm <span className="text-violet-500 font-semibold">Raphael</span>, a 31 year old software developer from Brazil. But it wasn't always like this. </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I started persuing a career in software development in 2010, when I was 19 years old. I was a
              student at the time, and I was studying <span className="text-violet-500 font-semibold">Computer Science</span> at the Pontifical Catholic University of Rio de Janeiro.
              I was also taking<span className="text-violet-500 font-semibold"> 3D</span> modeling classes at the same time.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I was really enjoying it. Maybe it was because I was learning something new, or maybe it was because I was
              learning something that I could use to create something that I could see imidiatly and I wasn't getting the same from
              the Computer Science classes. So I decided to <span className="text-violet-500 font-semibold">drop out</span> of the Computer Science course and persue a career in 3D modeling.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              In a matter of months I had already secured my student visa to study 3D modeling in the United States,
              I found a place to live, and I was ready to go. That adventure started on July of 2012. And there I was, in the United States,
              ready to start my new life. It actually went everything almolt as planned until it didn't. I was studying at <span className="font-semibold text-violet-500">Full Sail University</span>,
              and I was really enjoying it. I was learning a lot, and I was making a lot of friends, and creating a lot of connections.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              A few years passed, I graduated from Full Sail University, and I was ready to start my career as a 3D modeler. Got a <span className="text-violet-500 font-semibold">internship </span>
              at the Finals Department of my degree program. It lasted 6 months, and it made a huge impact on my life. Right after that I got a job
              at a small 3D modeling studio as a Remote 3D Hard Surface modeler. <span className="text-violet-500 font-semibold">But it wasn't paying the bills</span>. I <span className="text-violet-500 font-semibold">quit</span> that job and I started working
              as <span className="text-violet-500 font-semibold">Game Tester</span>.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              First I worked in the <span className="text-violet-500 font-semibold">localization team</span> checking if chinese games translated to english were correct. Then I worked in the QA team of
              team Scorpio for Experia. <span className="text-violet-500 font-semibold">I was working on the Xbox One X</span>. I was testing games, and I was making sure that they were working as intended. I was also
              testing the Xbox One X itself. I was making sure that the hardware was working as intended, cheking if the games were hitting the spected
              frame rates, and if the games were using the hardware to its full potential.
            </p>
            <p className="text-xs text-violet-500 md:text-md max-w-3xl font-extrabold my-4 text-center">
              Remember when I said sad everything went well until it didn't?
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              After all that came the end of <span className="text-violet-500 font-semibold">2017</span>. My work permit was about to expire, and <span className="text-violet-500 font-semibold">I had to go back to Brazil</span>. I was really sad about it, but I
              had to go back. I had to go back to Brazil. I tried getting back into <span className="text-violet-500 font-semibold">3D modeling</span>, but I couldn't find a job and the <span className="text-violet-500 font-semibold">joy was gone</span>. So, at the end of
              <span className="text-violet-500 font-semibold"> 2021</span>,
              I decided to fall back into something I started many years ago, <span className="text-violet-500 font-semibold">programming</span>.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I started learning programming again. I started with <span className="text-violet-500 font-semibold">Python</span>, taking the <span className="text-violet-500 font-semibold">IBM Data Science Professional Certificate</span> on Coursera. I thought that I
              could use that knowledge to get a job as a <span className="text-violet-500 font-semibold">Data Scientist</span>. But I was wrong. To be honest what I learned from that course was that <span className="text-violet-500 font-semibold">Data Science is boring</span>.
              My dad asked if I could help him with his insurance brokerage business. He had a lot of data that he needed to organize, and he needed a way to do it. I said let's do it.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I tried building a desktop application with <span className="text-violet-500 font-semibold">Python</span>, but to be honest <span className="text-violet-500 font-semibold">I had no idea what I was doing</span>. I was just following tutorials about the Kivy framework.
              Then I figure a Web Application would be better. I started learning <span className="text-violet-500 font-semibold">Django</span>. But nowhere I was told I'd need to learn <span className="text-violet-500 font-semibold">HTML, CSS, and JavaScript</span>. So I dove into those
              technologies as well. I was learning a lot. Again doing a lot of tutorials. But never creating things from scratch. So finally I decided to <span className="text-violet-500 font-semibold">give it another try</span> on my
              dad's problem.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I did the <span className="text-violet-500 font-semibold">jankiest </span>thing ever. I created a basic CRUD application with <span className="text-violet-500 font-semibold">NodeJS, Express, EJS</span> and <span className="text-violet-500 font-semibold">Bootstrap</span> on the front end. It was
              definitely not the best way to do it, but it worked. I was able to create a <span className="text-violet-500 font-semibold">Web Application</span> that could help my dad organize his data. But then he wanted to be way more dynamic. Because of that I went down the <span className="text-violet-500 font-semibold">React rabbit hole</span>.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I learned the basics, how to handle state and how to create stores(using <span className="text-violet-500 font-semibold">Redux</span>) in order to make the second version of the applacation for my dad. I was able to create a system, this time using <span className="text-violet-500 font-semibold">React, Redux, NodeJS, Express, MongoDB</span> and
              <span className="text-violet-500 font-semibold"> TailwindCSS</span>. It was a lot better than the first version. But I was still not satisfied. Single page application for what I wanted to do, wasn't the right path. So I decided to learn <span className="text-violet-500 font-semibold">NextJS</span>.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              I started then experimenting with <span className="text-violet-500 font-semibold">NextJs</span>. Switched to <span className="text-violet-500 font-semibold">PrismaORM</span> from <span className="text-violet-500 font-semibold">Mongoose</span> in order to work with <span className="text-violet-500 font-semibold">SQL </span>and learned <span className="text-violet-500 font-semibold">Typescript </span>in order to have <span className="text-violet-500 font-semibold">typesafety</span>. Honestly, I felt like I <span className="text-violet-500 font-semibold"></span>leveled up. Following that, I learned about <span className="text-violet-500 font-semibold">Clean Code</span> and the principles of <span className="text-violet-500 font-semibold">S.O.L.I.D.</span>. I started, once again, the project,
              this time I created a backend with <span className="text-violet-500 font-semibold">NodeJs</span>, <span className="text-violet-500 font-semibold">Express</span>, integrated it with <span className="text-violet-500 font-semibold">NextJs</span> in the frontend. In the frontend I used <span className="text-violet-500 font-semibold">ReactQuery</span> to get and update data and <span className="text-violet-500 font-semibold">TailwindCSS</span> to style the pages. I finally felt that I was able to create something consistent and usable in <span className="text-violet-500 font-semibold"></span>production, but the project didn't go forward.
              My dad's company decided to use an <span className="text-violet-500 font-semibold">Insuranse CRM</span> without integration with their website.
            </p>
            <p className="text-xs text-violet-500 md:text-md max-w-3xl font-extrabold my-4 text-center">
              Well, I decided to leave a few things out. But they're really important.
            </p>
            <p className="text-xs text-gray-700 md:text-md max-w-3xl indent-14">
              In the end of <span className="text-violet-500 font-semibold">2019</span> I met my <span className="text-violet-500 font-semibold">wife</span>, <span className="text-violet-500 font-semibold">Raquel</span>. She's <span className="text-violet-500 font-semibold">perfect</span>. She got me on a better path and <span className="text-violet-500 font-semibold">pushes</span> me to become a <span className="text-violet-500 font-semibold">better person</span> everyday. It's been a little bit over <span className="text-violet-500 font-semibold">three years</span> since we started dating and a few things happened since then. I got a <span className="text-violet-500 font-semibold">job</span> with another insurance brokerage company,
              we got <span className="text-violet-500 font-semibold">married</span> a little over <span className="text-violet-500 font-semibold">a year ago</span>, and we just had a baby <span className="text-violet-500 font-semibold">new born</span>, named <span className="text-violet-500 font-semibold">Ravi</span>. They are <span className="text-violet-500 font-semibold">my everything</span>.
              <p className="text-xs text-violet-500 md:text-md max-w-3xl font-extrabold my-4 text-end">
                January, 09th 2023
              </p>
            </p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Story;