import Head from "next/head";
import { FaEdit, FaTrash } from "react-icons/fa";

import Header from "../../components/Header";

import type { NextPage } from "next";
const todos = [
  {
    id: 1,
    title: "Learn Next.js",
    completed: false,
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
    author: {
      name: "wrathCodes",
    },
  },
  {
    id: 2,
    title: "Learn Tailwind CSS",
    completed: false,
    createdAt: "2021-08-01T00:00:00.000Z",
    updatedAt: "2021-08-01T00:00:00.000Z",
    author: {
      name: "wrathCodes",
    },
  },
];

const TodoApp: NextPage = (props) => {
  // const todos = trpc.todo.getAll.useQuery();

  return (
    <>
      <Head>
        <title>wrathCodes - TodoApp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-white to-gray-200">
        <div className="container mt-12 flex flex-col items-center justify-center gap-12 px-4">
          <h2 className="text-5xl font-extrabold tracking-tight text-violet-500 sm:text-[3rem]">Todo App</h2>

          <div className="flex w-7/12 flex-col items-center justify-center gap-4">
            {todos.map((todo) => (
              <Todo key={todo.id} {...todo} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default TodoApp;

interface ITodo {
  id: number;
  title: string;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
  author: {
    name: string;
  };
}

const Todo = ({ title, author, id }: ITodo) => {
  return (
    <div className="grid min-w-full grid-cols-1 gap-4 rounded-md bg-white p-4 shadow-md">
      <div className="flex flex-row items-center justify-between ">
        <div className="flex flex-row items-center">
          <input
            type="checkbox"
            id={`checkbox${ id }`}
            className="after:bg-[width:40px] peer relative
          mr-2 h-5 w-5 appearance-none rounded-sm border after:absolute after:top-0 after:left-0 after:h-full after:w-full after:rounded-sm
          after:bg-white
          after:bg-check-box after:bg-[length:40px] after:bg-center after:bg-no-repeat 
          after:opacity-0 after:shadow-md after:content-[''] checked:border-transparent checked:bg-violet-500 
          hover:ring hover:ring-violet-600 focus:outline-none"
          />
          <label
            htmlFor={`checkbox${ id }`}
            className="w-full cursor-pointer font-medium text-violet-500 peer-checked:text-gray-500/70 peer-checked:line-through"
          >
            <h3 className="text-2xl font-bold">{title}</h3>
          </label>
        </div>
        <div className="flex flex-row items-center justify-center gap-2">
          <button className="transform rounded-md bg-yellow-500 px-2 py-2 text-sm font-medium text-white hover:scale-110 hover:bg-yellow-500/80 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75">
            <FaEdit />
          </button>
          <button className="rounded-md bg-red-500 px-2 py-2 text-sm font-medium text-white transition hover:scale-110 hover:bg-red-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75">
            <FaTrash />
          </button>
        </div>
      </div>
      <p className="text-end text-gray-500">{author.name}</p>
    </div>
  );
};
